spring:
  datasource:
    url: jdbc:mariadb://localhost:3315/zenon
    username: zenon
    password: zenonPass

  security:
    user:
      name: admin
      password: admin

jwt:
  secret: araFhDdzAd4CIgmSQVkHAIDSZKvryh86b01lhBVGEcmFTUj67bEj45rSwK87k-g2Yx5xtYD2SjfRaUEVaJQCBA==
  expiration-ms: 3600000   # 1 heurew
